# CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps.py --config config_template.yaml

exp_arguments:
  # number of classes (Depends on class)
  n_classes: 2
  # name tag for saving generated figures and assets
  save_exp_code: output
  save_dir: /home/andrew/workspace/results/heatmaps/OTLS_3D_final/figures/cross
  # where to save raw asset files
  raw_save_dir: heatmaps/raw
  # where to save final heatmaps
  production_save_dir: heatmaps/production

  ## 2D
#  exp_dir: /home/andrew/workspace/results/MIL_OTLS_final_test_dropout/clf__cls-2__split-kf-5/seed--300__patch_128_step_128_2D_all_global_new__decay--0.0005__drop--0.5__prop--0.5__enc--resnet50_2d--imagenet_mean_HE__dec--attn--256--64__accum--10_aug--0__20230608-222454__ft--0
#  feats_path_block: /home/andrew/data/OTLS_full/inv/patch_128_step_128_2D_all_global/resnet50_2d_h5_patch_features/imagenet_mean_HE
#  feats_path_fine:  /home/andrew/data/OTLS_full/inv/patch_128_step_32_2D_all_global/resnet50_2d_h5_patch_features/imagenet_mean_HE

  ## 2plus1d
  ## 3D
#  exp_dir: /home/andrew/workspace/results/MIL_OTLS_final/clf__cls-2__split-kf-5/seed--300__patch_128-64_step_128-32_3D_all_global__decay--0.0005__drop--0.5__prop--0.5__enc--2plus1d--2plus1d_mean_HE__dec--attn--256--64__accum--10_aug--0__20230608-164205__ft--0
#  feats_path_block: /home/andrew/data/OTLS_full/inv/patch_128-64_step_128-32_3D_all_global/2plus1d_h5_patch_features/2plus1d_mean_HE
#  feats_path_fine: /home/andrew/data/OTLS_full/inv/patch_128-64_step_32-16_3D_all_global/2plus1d_h5_patch_features/imagenet_mean_HE


  ## 2plus1d PCA
#  exp_dir: /home/andrew/workspace/results/MIL_OTLS_final_test_dropout/seed--100__patch_128-64_step_128-32_3D_all_global__decay--0.0005__drop--0.5__prop--0.5__enc--2plus1d--2plus1d_mean_HE__dec--attn--256--64__accum--10_aug--0__20230608-163155__ft--0
#  feats_path_block: /home/andrew/data/OTLS_full/inv/patch_128-64_step_128-32_3D_all_global/2plus1d_h5_patch_features/2plus1d_mean_HE
#  feats_path_fine: ~

  ## Resnet50_3d
  ## 3D
#  exp_dir: /home/andrew/workspace/results/MIL_OTLS_final_test_dropout/clf__cls-2__split-kf-5/seed--100__patch_128-64_step_128-32_3D_all_global__decay--0.0005__drop--0.5__prop--0.5__enc--resnet50_3d--imagenet_mean_HE__dec--attn--256--64__accum--10_aug--0__20230609-122344__ft--0
#  feats_path_block: /home/andrew/data/OTLS_full/inv/patch_128-64_step_128-32_3D_all_global/resnet50_3d_h5_patch_features/imagenet_mean_HE
#  feats_path_fine: ~

  ## Cross
  exp_dir: /home/andrew/workspace/results/MIL_CT_trimmed_final/clf__cls-2__split-kf-5/seed--100__patch_128-32_step_128-32_3D_top12_global__decay--0.0005__drop--0.5__prop--0.5__enc--2plus1d--2plus1d_low_25k_top_1pct_mean_HE_aug__dec--attn--256--64__accum--10_aug--0__20230612-140119__ft--0
  feats_path_block: /home/andrew/data/OTLS_single_down--4x/patch_128-32_step_128-8_3D_all_global/2plus1d_h5_patch_features/imagenet_mean_HE
  feats_path_fine: /home/andrew/data/OTLS_single_down--4x/patch_128-32_step_32-8_3D_all_global/2plus1d_h5_patch_features/imagenet_mean_HE

  batch_size: 100
data_arguments:
  # where is data stored; can be a single str path or a dictionary of key, data_dir mapping
  data_dir: /media/andrew/OTLS/sagittal_new_down--4x/
  # where overlay data dir is stored (e.g. false coloring)
  data_overlay_dir: /home/andrew/data/false_color_down--4x/OTLS
  # csv list containing slide_ids (can additionally have seg/patch paramters, class labels, etc.)
  process_list: 'csv/OTLS/process_list_heatmap.csv'
  # preset file for segmentation/patching
  preset: ~
  # file extention for slides
  slide_ext: .tiff
  # label dictionary for str: interger mapping (optional)
  label_dict:
    0: 0
    1: 1
patching_arguments:
  # arguments for patching
  mask_dir: ~
  patch_size: 128
  patch_size_z: 32
  patch_mode: '3D'
  slice_mode: 'all'
  data_mode: 'OTLS'
  contour_fn: 'four_pt_easy'
  overlap: 0.75
  patch_level: 0
  custom_downsample: 1
model_arguments:
  # arguments for initializing feature extractor model
  extractor_name: '2plus1d'
  load_extractor_weights: True
  pretrained_extractor_path: 'imagenet'
  ckpt_path: 1
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: 0
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.4
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to also save the original H&E image
  save_orig: true
  # file extension for saving heatmap/original image
  save_ext: jpg
  # Convert to percentile
  convert_to_percentiles: False
  # Whether to have smooth contour
  contour: True
  # whether to use gaussian blur for further smoothing
  blur: True
  # whether to shift the 4 default corner points for checking if a patch is inside a foreground contour
  use_center_shift: true
  # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  use_roi: false
  # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  draw_fine_heatmap: True
  draw_blocky_heatmap: False
  # whether to binarize attention scores
  binarize: false
  binary_thresh: -1
  attn_mode: 'whole'
  custom_downsample: 1
  cmap_normalize: 'ig_slice'
  heatmap_score: 'ig'
  cmap_min: -1
  cmap_max: 1
  cmap: coolwarm
sample_arguments:
  sample_patch_score: 'ig'
  samples:
    - name: "topk_high"
      sample: true
      field: 'volume'
      seed: 1
      k: 10 # save top-k patches
      mode: topk
    - name: 'topk_low'
      sample: true
      field: 'volume'
      seed: 1
      k: 10 # save top-k patches
      mode: reverse_topk
#    - name: 'mid'
#      sample: true
#      field: 'volume'
#      seed: 1
#      k: 10
#      score_start: -0.1
#      score_end: 0.1
#      mode: range_sample



