# CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps.py --config config_template.yaml
---
exp_arguments:
  # number of classes
  n_classes: 2
  # name tag for saving generated figures and assets
  save_exp_code: output
  save_dir: /home/andrew/workspace/results/heatmaps/microCT_final/final/cross_-1_0.7_ver2
  # where to save raw asset files (Will be subdirectory of save_dir)
  raw_save_dir: heatmaps/raw
  # where to save final heatmaps (Will be subdirectory of save_dir)
  production_save_dir: heatmaps/production


  # 2plus1d PCA
#  exp_dir: /home/andrew/workspace/results/MIL_CT_trimmed_final/clf__cls-2__split-kf-5/seed--300__patch_128-32_step_128-32_3D_top12_global__decay--0.0005__drop--0.5__prop--0.5__enc--2plus1d--2plus1d_low_25k_top_1pct_mean_HE_aug__dec--attn--256--64__accum--10_aug--0__20230612-140730__ft--0
#  feats_path_block: /home/andrew/data/microCT_trimmed/patch_128-32_step_128-32_3D_top12_global/2plus1d_h5_patch_features/2plus1d_low_25k_top_1pct_mean_HE_aug
#  feats_path_fine: ~

  # Resnet503d PCA
#  exp_dir: /home/andrew/workspace/results/MIL_CT_trimmed_final/clf__cls-2__split-kf-5/seed--300__patch_128-32_step_128-32_3D_top12_global__decay--0.0005__drop--0.5__prop--0.5__enc--resnet50_3d--imagenet_low_25k_top_1pct_mean_HE__dec--attn--256--64__accum--10_aug--0__20230613-072214__ft--0
#  feats_path_block: /home/andrew/data/microCT_trimmed/patch_128-32_step_128-32_3D_top12_global/resnet50_3d_h5_patch_features/imagenet_low_25k_top_1pct_mean_HE
#  feats_path_fine: ~

  # 2plus1d plots
#  exp_dir: /home/andrew/workspace/results/MIL_CT_trimmed_final/clf__cls-2__split-kf-5/seed--400__patch_128-32_step_128-32_3D_top12_global__decay--0.0005__drop--0.5__prop--0.5__enc--2plus1d--2plus1d_low_25k_top_1pct_mean_HE_aug__dec--attn--256--64__accum--10_aug--0__20230612-141054__ft--0
#  feats_path_block: /home/andrew/data/microCT_trimmed/patch_128-32_step_128-32_3D_all_global/2plus1d_h5_patch_features/2plus1d_low_25k_top_1pct_mean_HE_subset
#  feats_path_fine: /home/andrew/data/microCT_trimmed/patch_128-32_step_32-16_3D_all_global/2plus1d_h5_patch_features/imagenet_mean_HE

  # Cross (Train: OTLS, test: CT)
  exp_dir: /home/andrew/workspace/results/MIL_OTLS_single_down--4x/clf__cls-2__split-kf-5/seed--200__patch_128-32_step_128-8_3D_all_global__decay--0.0005__drop--0.5__prop--0.5__enc--2plus1d--imagenet_mean_HE_noinv__dec--attn--256--64__accum--10_aug--0__20230707-141428__ft--0
  feats_path_block: /home/andrew/data/microCT_trimmed/patch_128-32_step_128-32_3D_all_global/2plus1d_h5_patch_features/2plus1d_low_25k_top_1pct_mean_HE
  feats_path_fine: /home/andrew/data/microCT_trimmed/patch_128-32_step_32-16_3D_all_global/2plus1d_h5_patch_features/imagenet_mean_HE

  batch_size: 50
data_arguments:
  # where is data stored; can be a single str path or a dictionary of key, data_dir mapping
  data_dir: /media/andrew/microCT/Prostate/trimmed_tiff
  # where overlay data dir is stored (e.g. false coloring)
  data_overlay_dir: /home/andrew/data/false_color/microCT_trimmed/tiff
  # csv list containing slide_ids (can additionally have seg/patch paramters, class labels, etc.)
  process_list: 'csv/CT/process_list_heatmap.csv'
  preset: None
  # file extention for slides
  slide_ext: .tiff
  # label dictionary for str: interger mapping (optional)
  label_dict:
    0: 0
    1: 1
patching_arguments:
  # arguments for patching
  mask_dir: ~
  patch_size: 128
  patch_size_z: 32
  patch_mode: '3D'
  slice_mode: 'all'
  data_mode: 'CT'
  contour_fn: 'four_pt_easy'
  overlap: 0.1
  patch_level: 0
  custom_downsample: 1
model_arguments:
  # arguments for initializing feature extractor model
#  extractor_name: 'resnet50_3d'
#  load_extractor_weights: True
#  pretrained_extractor_path: 'imagenet'
  extractor_name: '2plus1d'
  load_extractor_weights: True
  pretrained_extractor_path: 'imagenet'
  ckpt_path: 0
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: 0
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.4
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to also save the original H&E image
  save_orig: true
  # file extension for saving heatmap/original image
  save_ext: jpg
  # Convert to percentile
  convert_to_percentiles: False
  # whether to calculate percentile scores in reference to the set of non-overlapping patches
  use_ref_scores: False
  # whether to use gaussian blur for further smoothing
  blur: True
  # whether to shift the 4 default corner points for checking if a patch is inside a foreground contour
  use_center_shift: true
  # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  use_roi: false
  # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  draw_fine_heatmap: True
  draw_blocky_heatmap: False
  # whether to binarize attention scores
  binarize: false
  binary_thresh: -1
  attn_mode: 'whole'
  custom_downsample: 1
  #  heatmap_score: 'attn'
  #  cmap_normalize: 'slice'
  cmap_normalize: 'ig_slice'
  heatmap_score: 'ig'
  cmap_min: -1
  cmap_max: 1
  cmap: coolwarm
sample_arguments:
  sample_patch_score: 'ig'
  samples:
    - name: "topk_high"
      sample: true
      field: 'volume'
      seed: 1
      k: 20 # save top-k patches
      mode: topk
    - name: 'topk_low'
      sample: true
      field: 'volume'
      seed: 1
      k: 30 # save top-k patches
      mode: reverse_topk
#    - name: 'mid'
#      sample: true
#      field: 'volume'
#      seed: 1
#      k: 10
#      score_start: -0.1
#      score_end: 0.1
#      mode: range_sample



